language: node_js
node_js:
  - 8
  - 10
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --ignore-engines
script:
  - yarn ci
cache:
  yarn: true
  directories:
    - node_modules
